// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/icon-32x32.png
var resourceIcon32x32PngData []byte
var resourceIcon32x32Png = &fyne.StaticResource{
	StaticName:    "assets/icon-32x32.png",
	StaticContent: resourceIcon32x32PngData,
}
