#ifndef SCRIBE_FFI_H
#define SCRIBE_FFI_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef void *scribe_ClipboardHandle;

/**
 * Opaque pointer types for safe cross-FFI boundary object passing
 */
typedef void *scribe_HotkeyManagerHandle;

/**
 * Receives the action string the binding was registered with.
 */
typedef void (*scribe_HotkeyCallback)(const char*);

typedef void *scribe_SimulatorHandle;

#if defined(SCRIBE_MACOS)
extern bool CGEventSourceKeyState(int32_t state_id, uint16_t key);
#endif

/**
 * Get the last error message
 * Returns: C string (must be freed with scribe_free_string) or NULL if no error
 */
const char *scribe_get_last_error(void);

/**
 * Free a string allocated by Rust
 * This must be called for all strings returned by Rust functions
 */
void scribe_free_string(char *s);

scribe_ClipboardHandle scribe_clipboard_new(void);

/**
 * Null when the clipboard holds no text, including when it holds an image.
 */
char *scribe_clipboard_get_text(scribe_ClipboardHandle handle);

/**
 * 1 when the clipboard holds text, 0 when not. Distinguishes "copied a picture" from
 * "the copy never landed", which look identical through `get_text`.
 */
int scribe_clipboard_has_text(scribe_ClipboardHandle handle);

int scribe_clipboard_set_text(scribe_ClipboardHandle handle, const char *text);

/**
 * Empties the clipboard, so a following simulated copy landing becomes observable.
 */
int scribe_clipboard_clear(scribe_ClipboardHandle handle);

int scribe_clipboard_save(scribe_ClipboardHandle handle);

int scribe_clipboard_restore(scribe_ClipboardHandle handle);

void scribe_clipboard_free(scribe_ClipboardHandle handle);

scribe_HotkeyManagerHandle scribe_hotkey_manager_new(void);

int scribe_hotkey_clear(scribe_HotkeyManagerHandle handle);

int scribe_hotkey_register(scribe_HotkeyManagerHandle handle,
                           const char *binding,
                           const char *action,
                           scribe_HotkeyCallback callback);

int scribe_hotkey_start(scribe_HotkeyManagerHandle handle);

int scribe_hotkey_stop(scribe_HotkeyManagerHandle handle);

/**
 * Null when the listener is running. The caller frees the string with `scribe_free_string`.
 */
char *scribe_hotkey_listen_error(scribe_HotkeyManagerHandle handle);

void scribe_hotkey_manager_free(scribe_HotkeyManagerHandle handle);

scribe_SimulatorHandle scribe_simulator_new(void);

int scribe_simulate_select_all(scribe_SimulatorHandle handle);

int scribe_simulate_copy(scribe_SimulatorHandle handle);

int scribe_simulate_paste(scribe_SimulatorHandle handle);

/**
 * Releases modifiers still held from the triggering hotkey. Call once before any combo.
 */
int scribe_simulate_release_modifiers(scribe_SimulatorHandle handle);

void scribe_simulator_free(scribe_SimulatorHandle handle);

#endif  /* SCRIBE_FFI_H */
