#ifndef MYREVISER_FFI_H
#define MYREVISER_FFI_H

#pragma once

/* Generated with cbindgen:0.29.0 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef void *myreviser_ClipboardHandle;

/**
 * Opaque pointer types for safe cross-FFI boundary object passing
 */
typedef void *myreviser_HotkeyManagerHandle;

/**
 * Hotkey callback function type
 * The callback receives the action string that was registered
 */
typedef void (*myreviser_HotkeyCallback)(const char*);

typedef void *myreviser_SimulatorHandle;

/**
 * Get the last error message
 * Returns: C string (must be freed with myreviser_free_string) or NULL if no error
 */
const char *myreviser_get_last_error(void);

/**
 * Free a string allocated by Rust
 * This must be called for all strings returned by Rust functions
 */
void myreviser_free_string(char *s);

myreviser_ClipboardHandle myreviser_clipboard_new(void);

char *myreviser_clipboard_get_text(myreviser_ClipboardHandle handle);

int myreviser_clipboard_set_text(myreviser_ClipboardHandle handle, const char *text);

int myreviser_clipboard_save(myreviser_ClipboardHandle handle);

int myreviser_clipboard_restore(myreviser_ClipboardHandle handle);

void myreviser_clipboard_free(myreviser_ClipboardHandle handle);

myreviser_HotkeyManagerHandle myreviser_hotkey_manager_new(void);

int myreviser_hotkey_clear(myreviser_HotkeyManagerHandle handle);

int myreviser_hotkey_register(myreviser_HotkeyManagerHandle handle,
                              const char *binding,
                              const char *action,
                              myreviser_HotkeyCallback callback);

int myreviser_hotkey_start(myreviser_HotkeyManagerHandle handle);

int myreviser_hotkey_stop(myreviser_HotkeyManagerHandle handle);

void myreviser_hotkey_manager_free(myreviser_HotkeyManagerHandle handle);

myreviser_SimulatorHandle myreviser_simulator_new(void);

int myreviser_simulate_select_all(myreviser_SimulatorHandle handle);

int myreviser_simulate_copy(myreviser_SimulatorHandle handle);

int myreviser_simulate_paste(myreviser_SimulatorHandle handle);

void myreviser_simulator_free(myreviser_SimulatorHandle handle);

#endif  /* MYREVISER_FFI_H */
